"""rename industry to vertical

Revision ID: 10c0647f841a
Revises: cfced54e53be
Create Date: 2025-12-01 14:32:16.266605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c0647f841a'
down_revision = 'cfced54e53be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_study')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vertical', sa.String(length=100), nullable=True))
        batch_op.drop_column('industry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('vertical')

    op.create_table('case_study',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('standard', sa.VARCHAR(length=100), nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', sa.FLOAT(), nullable=True),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
